"""First migration

Revision ID: 39baa9b19fdd
Revises: 
Create Date: 2022-09-28 18:19:58.801882

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "39baa9b19fdd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveriess",
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("price_in_dollar", sa.Integer(), nullable=True),
        sa.Column("price_in_rub", sa.Float(), nullable=True),
        sa.Column("delivery_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("order_number", name=op.f("pk_deliveriess")),
    )
    op.create_index(
        op.f("ix_deliveriess_number"), "deliveriess", ["number"], unique=False
    )
    op.create_index(
        op.f("ix_deliveriess_order_number"),
        "deliveriess",
        ["order_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveriess_order_number"), table_name="deliveriess")
    op.drop_index(op.f("ix_deliveriess_number"), table_name="deliveriess")
    op.drop_table("deliveriess")
    # ### end Alembic commands ###
